version: '3.8'

services:
  postgres_core:
    image: postgres:15
    environment:
      POSTGRES_DB: core_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - pgdata_core:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  postgres_user:
    image: postgres:15
    environment:
      POSTGRES_DB: user_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - pgdata_user:/var/lib/postgresql/data
    ports:
      - "5434:5432"

  postgres_account:
    image: postgres:15
    environment:
      POSTGRES_DB: account_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - pgdata_account:/var/lib/postgresql/data
    ports:
      - "5435:5432"

  core-service:
    build:
      context: .
      dockerfile: apps/core-service/Dockerfile
    environment:
      DB_HOST: postgres_core
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: core_db
    depends_on:
      - postgres_core
    ports:
      - "3000:3000"

  user-service:
    build:
      context: .
      dockerfile: apps/user-service/Dockerfile
    environment:
      DB_HOST: postgres_user
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: user_db
    depends_on:
      - postgres_user
    ports:
      - "3001:3001"

  account-service:
    build:
      context: .
      dockerfile: apps/account-service/Dockerfile
    environment:
      DB_HOST: postgres_account
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: account_db
    depends_on:
      - postgres_account
    ports:
      - "3002:3002"

  # zookeeper:
  #  image: bitnami/zookeeper:latest
  #  container_name: zookeeper
  #  ports:
  #    - "2181:2181"
  #  environment:
  #    - ALLOW_ANONYMOUS_LOGIN=yes

  #kafka:
  #  image: bitnami/kafka:3.4
  #  container_name: kafka
  #  ports:
  #    - "9092:9092"
  #  environment:
  #    - KAFKA_CFG_BROKER_ID=1
  #    - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
  #    - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
  #    - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
  #    - ALLOW_PLAINTEXT_LISTENER=yes
  #    - KAFKA_CFG_OFFSETS_TOPIC_REPLICATION_FACTOR=1
  #    - KAFKA_CFG_TRANSACTION_STATE_LOG_REPLICATION_FACTOR=1
  #    - KAFKA_CFG_TRANSACTION_STATE_LOG_MIN_ISR=1
  #  depends_on:
  #    - zookeeper

volumes:
  pgdata_core:
  pgdata_user:
  pgdata_account:
